### ISSUE TITLE
关于自部署问题！！！

### ISSUE THREAD

**Issue by Stanley-baby** [yesmore/vmail#1]
请问turso sqlite部分在网页设置好了之后一定要在Linux 终端执行吗？
也就说必须本地运行或者需要一个服务器对吗？

**Comment by yesmore** [comment]
不是，turso cli 支持 mac/Linux/win，我用 Linux 因为不需要额外环境，方便安装一点

**Comment by Stanley-baby** [comment]
意思是turso cli必须本地部署运行或者在服务器上运行对吗？比如我在 Mac本地部署，那我Mac 一关机，是不是就不能用了？ 发件人: Juiçe ***@***.***>日期: 星期一, 2024年3月18日 11:51收件人: yesmore/vmail ***@***.***>抄送: Stanley-baby ***@***.***>, Author ***@***.***>主题: Re: [yesmore/vmail] 关于自部署问题！！！ (Issue #1)不是，turso cli 支持 mac/Linux/win，我用 Linux 因为不需要额外环境，方便安装一点—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by yesmore** [comment]
为什么是本地部署呢，教程并没有提到本地部署，只有本地开发，worker 是部署在 cf 上的，上线就能用，前端可以本地开发跑端口，但是域名不匹配不能用的，需要部署后才能用

**Comment by Stanley-baby** [comment]
就是终端执行这一步是本地开发对吧？发件人: Juiçe ***@***.***>日期: 星期一, 2024年3月18日 12:00收件人: yesmore/vmail ***@***.***>抄送: Stanley-baby ***@***.***>, Author ***@***.***>主题: Re: [yesmore/vmail] 关于自部署问题！！！ (Issue #1)为什么是本地部署呢，教程并没有提到本地部署，只有本地开发，worker 是部署在 cf 上的，上线就能用，前端可以本地开发跑端口，但是域名不匹配不能用的，需要部署后才能用—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by yesmore** [comment]
对呀，只是用本地终端登录 turso 的，然后链接远程数据库操作，不算是本地开发

**Comment by Stanley-baby** [comment]
好哒明白了   我这就弄一个🥰 发件人: Juiçe ***@***.***>日期: 星期一, 2024年3月18日 12:12收件人: yesmore/vmail ***@***.***>抄送: Stanley-baby ***@***.***>, Author ***@***.***>主题: Re: [yesmore/vmail] 关于自部署问题！！！ (Issue #1)对呀，只是用本地终端登录 turso 的，然后链接远程数据库操作，不算是本地开发—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
