### ISSUE TITLE
官网版摘要正常显示，点进去无法显示邮件内容

### ISSUE THREAD

**Issue by fishhh666** [yesmore/vmail#11]
外部正常：
![image](https://github.com/yesmore/vmail/assets/161964499/1023102d-d04a-4688-8bbe-6d1fcf21fd29)

点进去：
![image](https://github.com/yesmore/vmail/assets/161964499/148315b1-edb1-4d32-81b9-19861bc153aa)

控制台报错：
![image](https://github.com/yesmore/vmail/assets/161964499/5cfa7fc2-fa5f-4d2f-ae34-b3eee8ee1116)

其他：Microsoft Edge
版本 122.0.2365.92 (正式版本) (64 位)

**Comment by yesmore** [comment]
排查了一下，数据库存储的对应字段是Null，可能是worker接收的源数据有问题，先mark上
