### ISSUE TITLE
建议生成的邮箱可以通过一个key来固定

### ISSUE THREAD

**Issue by zau999** [yesmore/vmail#12]
比如一个邮箱对应一个key, 输入这个key,得到固定的邮箱

这个key可以是一个规则,一个算法. 不需要存储到数据库. 

比如随机生成一个key, 然后这个key通过某种hash运算得到一个hash,
然后用这个hash,去词典表里找单词组合成邮箱名. 或者直接就用这个hash作为邮箱名也行.

这样就可以有一个固定的邮箱名了. 其它人也拿不到这个邮箱.

**Comment by yesmore** [comment]
这样算长期邮箱了，并且现在支持自定义过期时间长短了，设置 `EXPIRY_TIME` 变量实现
