### ISSUE TITLE
是否是借鉴

### ISSUE THREAD

**Issue by wanglihuaya** [yesmore/vmail#14]
亲爱的开发者您好：
很尊重和敬佩你花时间在开源项目上
不过和之前看过的一个项目非常相似，[这个](https://github.com/akazwz/smail)
如果是有借鉴或者另一个作者有提供帮助的话 希望也可以尊重开源，@一下原作者

**Comment by wanglihuaya** [comment]
https://github.com/akazwz/smail

**Comment by yesmore** [comment]
> 亲爱的开发者您好：
> 很尊重和敬佩你花时间在开源项目上
> 不过和之前看过的一个项目非常相似，[这个](https://github.com/akazwz/smail)
> 如果是有借鉴或者另一个作者有提供帮助的话 希望也可以尊重开源，@一下原作者

readme 最底部

**Comment by innocces** [comment]
emmm~ 感觉已经不是借鉴的程度了

从你的初始提交来看。你甚至连变量名都没改。如果你只是想要自己封装UI应该 Foke 出来。你甚至没有着重的标注原作者。你这个行为有点过分了。

https://github.com/yesmore/vmail/commit/04e1610f53e9447e1578e9661493e776d987831a#diff-31762727b4ffc346f61874faa65a186d6fccf7b257d59acf4e35dfe4bd5d9304R1

原作者的：
https://github.com/akazwz/smail/blob/ed2f7327e729e4dd5a5b7ba3a6fcd7b44a5abe83/apps/email-api/src/index.ts#L24

你的：
https://github.com/yesmore/vmail/blob/267e526138181a33d89f1bccedb8965788474514/apps/email-api/src/index.ts#L25

**Comment by wanglihuaya** [comment]
感谢理解和支持
