### ISSUE TITLE
程序员小白请教第4步

### ISSUE THREAD

**Issue by liuwleo** [yesmore/vmail#15]
作者你好，
程序员小白想部署，但是到第四部对于变量的编辑和代码推送到github不会，能否细说一下，谢谢先！

**Comment by yesmore** [comment]
搜索关键词 `github 代码推送到远程仓库`，`vercel 从 github 导入仓库并填写环境变量`

**Comment by yesmore** [comment]
已更新文档，建议使用一键部署

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-link=https%3A%2F%2Fgithub.com%2Fyesmore%2Fvmail&env=COOKIES_SECRET&env=TURNSTILE_KEY&env=TURNSTILE_SECRET&env=TURSO_DB_RO_AUTH_TOKEN&env=TURSO_DB_URL&env=EMAIL_DOMAIN&project-name=vmail&repository-name=vmail)

**Comment by liuwleo** [comment]
感谢。关于变量中第一个cookie密钥这个从哪里获取，谢谢。

**Comment by yesmore** [comment]
> 感谢。关于变量中第一个cookie密钥这个从哪里获取，谢谢。

随便填写，比如`abcdefg123567`

**Comment by liuwleo** [comment]
原来如此，多谢指点！

**Comment by liuwleo** [comment]
Vercel尝试一键部署，输入变量，deploy后显示“An unexpected error occurred. Our team has already been notified and are working to resolve the issue, please try again shortly.”。之前步骤应该都对。求助

**Comment by yesmore** [comment]
> Vercel尝试一键部署，输入变量，deploy后显示“An unexpected error occurred. Our team has already been notified and are working to resolve the issue, please try again shortly.”。之前步骤应该都对。求助

感谢反馈，那个部署链接写错了，已修复

**Comment by liuwleo** [comment]
可以部署了，但是出现404😂
<img width="502" alt="image" src="https://github.com/yesmore/vmail/assets/49121177/4ef0f2d8-d95f-438e-833a-36db13fc961d">

**Comment by liuwleo** [comment]
修改参数后重新部署页面出现，但是尝试用域名访问提示“XX将您重定向的次数过多。” 用Vercel的域名可以打开页面，但是Validator错误：
<img width="394" alt="image" src="https://github.com/yesmore/vmail/assets/49121177/14f807e2-58fd-4415-a684-023d0127c21b">
排除了一下，不太确认哪个配置出现问题。求助

**Comment by yesmore** [comment]
需要配置ssl加密模式为完全或者完全（严格）
![{66FC66B2-BF5B-42e0-A377-CF89B3D9347C}](https://github.com/yesmore/vmail/assets/89140804/3d12d7ab-5c6c-448d-ba2b-45bf03b16958)
