### ISSUE TITLE
关于解析域名

### ISSUE THREAD

**Issue by johe123qwe** [yesmore/vmail#2]
请问教程中提到的“部署成功后在 cloudflare 添加域名解析到对应平台”，不清楚解析什么域名，这步怎么操作？谢谢！

**Comment by yesmore** [comment]
比如说在vercel部署，添加自定义域名后，需要在 cloudflare 的域名DNS中加上A记录：
![{A5E085BF-B33B-4a5d-A650-EC37ACBB54D6}](https://github.com/yesmore/vmail/assets/89140804/825a957a-9e14-4b71-a035-7b50777f63e2)
![{6B6DD95F-F665-4ab8-8C28-ACE961AE7863}](https://github.com/yesmore/vmail/assets/89140804/b6ebbeac-8f7c-403e-ab1b-89d444e267ba)

**Comment by johe123qwe** [comment]
以上问题已经解决。谢谢！
首页打开后生成的邮箱不是我的域名，这个怎么解决呢？
![Monosnap Vmail - Virtual Temporary Email 2024-03-18 11-58-59](https://github.com/yesmore/vmail/assets/22858214/94a9db14-11f0-4c25-8b1e-7b80a4e7c7e5)

**Comment by yesmore** [comment]
> 以上问题已经解决。谢谢！
> 首页打开后生成的邮箱不是我的域名，这个怎么解决呢？
> ![Monosnap Vmail - Virtual Temporary Email 2024-03-18 11-58-59](https://github.com/yesmore/vmail/assets/22858214/94a9db14-11f0-4c25-8b1e-7b80a4e7c7e5)
> 

在本地全局搜索一下 vmail.dev，替换掉
