### ISSUE TITLE
部署 email worker

### ISSUE THREAD

**Issue by luckyzwei** [yesmore/vmail#3]
"""2.部署 email worker

git clone https://github.com/yesmore/vmail

cd vmail

# 安装依赖
pnpm install"""

请问这个步骤是在那里执行命令

**Comment by yesmore** [comment]
命令行终端，需要有node环境

**Comment by luckyzwei** [comment]
嗯，我本地命令行終端執行了是怎麽部署到worker上去的呢

**Comment by yesmore** [comment]
文档有
cd apps/email-worker
pnpm run deploy
