### ISSUE TITLE
求助，关于 TURNSTILE_KEY 和 TURNSTILE_SECRET 获取方法

### ISSUE THREAD

**Issue by Skyxim** [yesmore/vmail#7]
TURNSTILE_KEY
TURNSTILE_SECRET

请问这两个在哪获取，Key只写了一个从 Cloudflare 网站获取没写具体是什么

**Comment by HarrisonWang** [comment]
这里：https://www.cloudflare-cn.com/products/turnstile/

**Comment by yesmore** [comment]
如图
![](https://img.inke.app/file/4a0ca12e02543119e0603.png)
![](https://img.inke.app/file/c29ecc73dc5ff05bbd026.png)

**Comment by Skyxim** [comment]
感谢
