### ISSUE TITLE
用不了  deploy之后直接报错 Worker threw exception

### ISSUE THREAD

**Issue by bfgnfgmhm** [yesmore/vmail#9]
git clone https://github.com/yesmore/vmail
cd vmail
pnpm install
vim vmail/apps/email-worker/wrangler.toml
cd apps/email-worker
pnpm run deploy
> email-worker@0.0.0 publish /opt/www/vmail/apps/email-worker
> wrangler publish

 ⛅️ wrangler 3.22.4 (update available 3.34.2)
-------------------------------------------------------
▲ [WARNING] `wrangler publish` is deprecated and will be removed in the next major version.

  Please use `wrangler deploy` instead, which accepts exactly the same arguments.

Your worker has access to the following bindings:
- Vars:
  - TURSO_DB_AUTH_TOKEN: "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9...."
  - TURSO_DB_URL: "libsql://vm-xxx.turso.io"
  - EMAIL_DOMAIN: "xxxx.eu.org"
Total Upload: 484.10 KiB / gzip: 95.85 KiB
Uploaded email-worker (1.76 sec)
Published email-worker (0.23 sec)
  https://email-worker.xxxx.workers.dev
Current Deployment ID: bfe375c0-ec3f-4ee7-9ffb-87d0d4535269

访问  https://email-worker.xxxx.workers.dev 提示：
Error 1101 Ray ID: 866e3a28aeb8e656 • 2024-03-19 14:42:06 UTC
Worker threw exception

**Comment by yesmore** [comment]
https://email-worker.xxxx.workers.dev/ 本身不能访问，还要部署前端才行

**Comment by bfgnfgmhm** [comment]
汗。。Vercel 要是必须的，就在准备工作里都列出来吧，看文档的感觉就是worker和Vercel 是二选一的关系。

**Comment by yesmore** [comment]
可以
